# Generated by Django 5.1 on 2024-08-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowToWork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('id_usr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr1', to='HowToWork.usuario')),
                ('id_usr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr2', to='HowToWork.usuario')),
            ],
        ),
    ]
