# Generated by Django 5.1 on 2024-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowToWork', '0002_solicitudamistad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='amigos',
            field=models.ManyToManyField(blank=True, related_name='amigos', to='HowToWork.usuario'),
        ),
    ]
