# Generated by Django 5.1 on 2024-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowToWork', '0003_usuario_amigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='amigos',
            field=models.ManyToManyField(blank=True, to='HowToWork.usuario'),
        ),
    ]
