# Generated by Django 5.1 on 2024-08-13 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowToWork', '0004_alter_usuario_amigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('usuarios', models.ManyToManyField(related_name='proyectousuario', to='HowToWork.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('id_usr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr1proyecto', to='HowToWork.usuario')),
                ('id_usr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr2proyecto', to='HowToWork.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('notas', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Completado'), (2, 'Necesita Revision')], default=0)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HowToWork.proyecto')),
            ],
        ),
    ]
