# Generated by Django 5.1 on 2024-08-14 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowToWork', '0005_proyecto_solicitudproyecto_tarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudamistad',
            name='id_usr2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='id_usr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr1proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudamistad',
            name='id_usr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='id_usr2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usr2proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(related_name='proyectousuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
