# Generated by Django 5.1 on 2024-08-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HowToWork', '0006_alter_solicitudamistad_id_usr2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudproyecto',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_proyecto', to='HowToWork.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='proyectousuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
